# Generated by Django 4.0.4 on 2022-06-28 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_brand',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car_model',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.car_brand'),
        ),
        migrations.AlterField(
            model_name='car_model',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
